README.md
examples/fargate-spot/main.tf
main.tf
variables.tf

- Add support + example for FARGATE-SPOT capacity provider
- Add support for task definition options: placement_constraints, proxy_configuration, volume and docker_volume_configuration
- Update docs

Add support for FARGATE-SPOT capacity provider and extend task definition

---

README.md
examples/fargate-efs/main.tf
main.tf
variables.tf

1. Add support for container timeouts (var.task_start_timeout and var.task_stop_timeout)
2. Add support for container mountPoints (var.task_mount_points)
3. Add example for fargate with volume and efs mount
PR addresses issue:
https://github.com/umotif-public/terraform-aws-ecs-fargate/issues/15

Add full support for volumes and container timeouts

---

.pre-commit-config.yaml
README.md
examples/core/main.tf
main.tf
variables.tf

- Allow for security group to be created and deleted without failing. 
- sg_name_prefix variable add to allow for custom name.
**Breaking change,** this will require to create a new security group and old ecs task will be blocking deletion of old security group. This can be solved by removing manually old tasks. New tasks will be running at that stage so application will not experience any downtime. (This is applicable when upgrading module from 1.X to 2.X.
This PR with form part of 2.0.0 release.

Improve security group creation/deletion and switch to using prefix

---

.pre-commit-config.yaml
README.md
main.tf
variables.tf
versions.tf

- Add support for ecs_service argument force_new_deployment
- Add minimum provider version and set to ~> 2.63
This will be part of 3.0.0 release.

Lock minimum version of provider and add force_new_deployment

---

.pre-commit-config.yaml
CHANGELOG.md
README.md
main.tf
outputs.tf
versions.tf

Add support for efs volume configuration:
- transit_encryption
- transit_encryption_port
- authorization_config

Add full for volume configuration

---

main.tf

Fix warning "Interpolation-only expressions are deprecated"

Fix warning "Interpolation-only expressions are deprecated"

---

.pre-commit-config.yaml
CHANGELOG.md
README.md
examples/core/main.tf
examples/fargate-efs/main.tf
examples/fargate-spot/main.tf
main.tf
variables.tf
versions.tf

- Min version of terraform set to 13
- Min version of terraform provider set to 3.13
- Add support for terraform 14
- Drop support for terraform 12
- Support for `wait_for_steady_state` ecs service parameter
- Update examples and docs
- remove null service, terraform 0.13 supports depends_on block for modules
This PR forms version 5.0.0 of the module

Major upgrade to v5

---

main.tf
variables.tf

Fix issue #27: Added in variable `task_container_secrets` and a conditional entry into the task definition JSON to pass secrets to it.

Add secrets to task defintion

---

.gitignore
README.md
examples/fargate-efs/main.tf
examples/fargate-spot/main.tf
examples/multiple-target-groups/main.tf
main.tf
outputs.tf
variables.tf

**New Feature:**
- Added functionality to allow the ability to register multiple target groups for an ECS service. Read more here: [Register multiple target groups](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/register-multiple-targetgroups.html)
It is now **required** to set `target_groups` if you want to register a target group(s) to ECS Service else set `loadbalanced = false`. 
**Fixes & Improvements:**
- Upgrades and cleanups in examples
- Switch to using default VPC and subnets in examples
- New example to demonstrate multiple target groups for ECS service
- Remove any unused variables

Add support for registering multiple target groups with a service

---

examples/core/main.tf
examples/fargate-efs/main.tf
examples/fargate-spot/main.tf

Updating examples with `target_group_name` parameter.

Add missing 'target_group_name' parameter in examples

---

.pre-commit-config.yaml
CHANGELOG.md
README.md
data.tf
main.tf
variables.tf
versions.tf

- New variable added `enable_execute_command`
- Minimum terraform aws provider version is set to 3.34.0

Add support for enable_execute_command

---

main.tf

add tags iam role

---

data.tf
main.tf

Fetches the latest task definition and supplies that to ECS service definition to avoid issues in case an external CI/CD system is involved.
Fixes issue https://github.com/umotif-public/terraform-aws-ecs-fargate/issues/40

Add support to pick latest task definition

---

CHANGELOG.md
README.md
main.tf

The `deregistration_delay` attribute of a Target Group is set to 300 seconds by default (1)
as a conservatively safe value. However, if a service owner knows that their connections stop faster
it makes sense to reduce the delay to speed up deployments. This PR makes the customization
possible via the module.
Please let me know if you need me to update any additional files (i.e. CHANGELOG.md)
[1] https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group#deregistration_delay

Make deregistration_delay attribute customizable for ALB Target Groups

---

.pre-commit-config.yaml
CHANGELOG.md
README.md
examples/core/main.tf
examples/fargate-efs/main.tf
examples/fargate-spot/main.tf
examples/multiple-target-groups/main.tf
versions.tf

This PR was to ensure the module is 4.0.0 compatible. 
Minor set of updates: 
1. Use the latest pre-commit version
2. Refactor `capacity_providers` attribute within `aws_ecs_cluster` resource to use `aws_ecs_cluster_capacity_providers` resource.
3. Update minimum terraform version to `0.13.7`

Refactor examples to work with provider 4.0.0+

---

.pre-commit-config.yaml
CHANGELOG.md
README.md
examples/multiple-target-groups/main.tf
main.tf
versions.tf

This commit enables the module to prefer the `target_groups` list of `container_port` and `protocol` over `task_container_port`.
If the target_groups does not have port and protocol specified, current behavior continues.

Enable containerDefinitions portMappings to use target_groups container_ports

---

CHANGELOG.md
README.md
main.tf
variables.tf

Currently the module doesn't support the option to specify run_time platform. We had a use case to run tasks based on ARM64 containers which can only made possible by specifying the run_time platform block in the task definition resource.

Allow option to customise run_time platform

---

.gitignore
.pre-commit-config.yaml
CHANGELOG.md
README.md
examples/core/main.tf
main.tf
variables.tf
versions.tf

- feature: Adding `entryPoint` to [task definitions parameters](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_environment)
- chore: update pre-commit version
- chore: update minimum terraform CLI version

Add entrypoint to task definition parameters

---

main.tf
variables.tf

Add readonlyRootFilesystem to container_definition. It's required by AWS security assessment.

Add readonlyRootFilesystem to container_definition

---

README.md
main.tf
variables.tf

Defined a new input variable which allow the user to create the default egress rule or not. This gives the opportunity to not allow all outgoing traffic. 
The Allow all outgoing traffic could be problematic for teams

Make egress rule configurable

---

.pre-commit-config.yaml
CHANGELOG.md
README.md
examples/core/main.tf
examples/core/versions.tf
examples/external-container-definitions/main.tf
examples/external-container-definitions/versions.tf
examples/fargate-efs/main.tf
examples/fargate-efs/versions.tf
examples/fargate-spot/main.tf
examples/fargate-spot/versions.tf
examples/multiple-target-groups/main.tf
examples/multiple-target-groups/versions.tf
main.tf
versions.tf

Module is now 5.x compatibile
**BREAKING CHANGE**
`container_name` now must be set for target_group. 
This variable can be set via `var.container_name` or can be set via `var.name_prefix`. 
The purpose behind this change is to accommodate the requirement of using an external container definition where the container name(s) are set externally to the module and, therefore, must be set within `target_group`.

Upgrade to 5.x + Fixes
